apiVersion: v1
kind: Service
metadata:
  name: {{ include "audit-service.name" . }}
  namespace: {{ include "palisade.namespace" . }}
  labels:
{{ include "audit-service.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8086
      protocol: TCP
      name: web
  selector:
    app.kubernetes.io/name: {{ include "audit-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
