container:
  args:
    - --api.insecure
    - --accesslog
    - --entrypoints.web.Address=:80
    - --providers.kubernetesingress=true
    - --providers.kubernetescrd.namespaces=kube-system,default,dev,uat
    - --ping=true

admin:
  port:  8080