apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: ingressroutes.traefik.containo.us
    namespace: kube-system
    annotations:
      "helm.sh/hook": crd-install
      "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
    group: traefik.containo.us
    versions:
        - name: v1alpha1
          served: true
          storage: true
    names:
        kind: IngressRoute
        plural: ingressroutes
        singular: ingressroute
    scope: Namespaced

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: ingressroutetcps.traefik.containo.us
    namespace: kube-system
    annotations:
        "helm.sh/hook": crd-install
        "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
    group: traefik.containo.us
    versions:
        - name: v1alpha1
          served: true
          storage: true
    names:
        kind: IngressRouteTCP
        plural: ingressroutetcps
        singular: ingressroutetcp
    scope: Namespaced

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: middlewares.traefik.containo.us
    namespace: kube-system
    annotations:
        "helm.sh/hook": crd-install
        "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
    group: traefik.containo.us
    versions:
        - name: v1alpha1
          served: true
          storage: true
    names:
        kind: Middleware
        plural: middlewares
        singular: middleware
    scope: Namespaced

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: tlsoptions.traefik.containo.us
    namespace: kube-system
    annotations:
        "helm.sh/hook": crd-install
        "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
    group: traefik.containo.us
    versions:
        - name: v1alpha1
          served: true
          storage: true
    names:
        kind: TLSOption
        plural: tlsoptions
        singular: tlsoption
    scope: Namespaced
