# Copyright 2019 Crown Copyright
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
launcher:
  default-service:
    profiles: jvm
    loader: org.springframework.boot.loader.JarLauncher
    main: uk.gov.gchq.palisade.service.policy.PolicyApplication
    classpath: SERVICE/target/SERVICE-0.4.0-SNAPSHOT-exec.jar:../Palisade-examples/example-library/target/example-library-0.4.0-SNAPSHOT-jar-with-dependencies.jar
    log: SERVICE-jvm.log